;;;; Tests for per-process heaps (sb-fiber's heap API), one per entry
;;;; point and error case.  Fiber integration and stress coverage lives
;;;; in process-heap.impure.lisp.

;;;; This software is part of the SBCL system. See the README file for
;;;; more information.

(unless (and (member :sb-thread *features*)
             (member :sb-process-heaps *features*)
             (member :sb-fiber *features*))
  (invoke-restart 'run-tests::skip-file))

;;; The pure-test runner deletes the packages a file creates once it is
;;; done with it, but REQUIRE still remembers the module, so reload the
;;; contrib when an earlier file's copy has been deleted.
(unless (find-package "SB-FIBER")
  (setf *modules* (remove "SB-FIBER" *modules* :test #'string=)))
(require :sb-fiber)
(use-package :sb-fiber)

;;; Errors that escape a test must not be recorded by the harness while
;;; the test's heap is still installed, or the failure records themselves
;;; become dangling process objects once the heap is released.
(defmacro with-test-heap ((var &rest args) &body body)
  `(let ((,var (make-heap ,@args)))
     (unwind-protect
          (handler-bind ((error (lambda (c)
                                  (declare (ignore c))
                                  (sb-fiber::%switch-heap 0))))
            ,@body)
       (release-heap ,var))))

;;; --- Lifecycle and ownership ---

(with-test (:name (:process-heap :make-and-release))
  (let ((h (make-heap :name "h")))
    (assert (heap-p h))
    (assert (heap-alive-p h))
    (assert (string= (heap-name h) "h"))
    (assert (plusp (heap-id h)))
    (assert (zerop (heap-bytes-allocated h)))
    (release-heap h)
    (assert (not (heap-alive-p h)))
    (assert (heap-released-p h))
    ;; Double release is a no-op.
    (release-heap h)))

(with-test (:name (:process-heap :with-heap :ownership))
  (with-test-heap (h)
    (assert (null (current-heap)))
    (let (obj global)
      (with-heap (h)
        (assert (eq (current-heap) h))
        (setf obj (list (make-array 3) (make-string 3 :initial-element #\s) 1.5d0)))
      (setf global (list 1 2))
      (assert (null (current-heap)))
      (assert (eq (object-heap obj) h))
      (assert (eq (object-heap (first obj)) h))
      (assert (eq (object-heap (second obj)) h))
      (assert (null (object-heap global)))
      (assert (null (object-heap 42)))
      (assert (null (object-heap 'car)))
      (assert (= (sb-vm::object-owner obj) (heap-id h)))
      (assert (zerop (sb-vm::object-owner global)))
      (assert (plusp (heap-bytes-allocated h)))
      (assert (plusp (heap-page-count h))))))

(with-test (:name (:process-heap :with-heap :nesting-and-unwind))
  (with-test-heap (a)
    (with-test-heap (b)
      (with-heap (a)
        (assert (eq (current-heap) a))
        (with-heap (b)
          (assert (eq (current-heap) b))
          (without-heap
            (assert (null (current-heap)))
            (assert (null (object-heap (list 1)))))
          (assert (eq (current-heap) b)))
        (assert (eq (current-heap) a))
        (catch 'out
          (with-heap (b)
            (throw 'out nil)))
        (assert (eq (current-heap) a)))
      (assert (null (current-heap))))))

(with-test (:name (:process-heap :without-heap :allocates-globally))
  (with-test-heap (h)
    (with-heap (h)
      (let ((local (list 1))
            (global (without-heap (list 2))))
        (assert (eq (object-heap local) h))
        (assert (null (object-heap global)))))))

(with-test (:name (:process-heap :released-heap-errors))
  (let ((h (make-heap)))
    (release-heap h)
    (assert-error (with-heap (h) nil) dead-heap-error)
    (assert-error (heap-gc h) dead-heap-error)
    (assert-error (send-message h 1) dead-heap-error)))

(with-test (:name (:process-heap :heap-gc :requires-current))
  (with-test-heap (h)
    (assert-error (heap-gc h) heap-not-current-error)
    (assert-error (heap-gc) no-current-heap-error)
    (assert-error (receive-message) no-current-heap-error)))

;;; --- Local collection ---

(with-test (:name (:process-heap :heap-gc :retains-live-data))
  (with-test-heap (h :gc-threshold 0)
    (with-heap (h)
      (let ((keep (loop for i below 500
                        collect (cons i (make-array 4 :initial-element i))))
            (str (make-string 100 :initial-element #\x))
            (table (make-hash-table :test 'equal)))
        (dotimes (i 1000) (setf (gethash (format nil "k~D" i) table) i))
        (dotimes (i 50000) (make-list 10))
        (let ((before (heap-bytes-allocated h)))
          (assert (heap-gc h))
          (assert (= (heap-gc-count h) 1))
          (assert (< (heap-bytes-allocated h) before))
          (assert (= (heap-bytes-live h) (heap-bytes-allocated h))))
        (loop for (i . v) in keep for j from 0
              do (assert (= i j))
                 (assert (= (aref v 0) j)))
        (assert (= (length str) 100))
        (assert (every (lambda (c) (char= c #\x)) str))
        (assert (= (hash-table-count table) 1000))
        (dotimes (i 1000)
          (assert (= (gethash (format nil "k~D" i) table) i)))
        (assert (null (verify-heap h)))))))

(with-test (:name (:process-heap :heap-gc :large-objects))
  (with-test-heap (h :gc-threshold 0)
    (with-heap (h)
      (let ((big (make-array 100000 :initial-element 7))
            (garbage nil))
        (dotimes (i 20) (push (make-array 100000) garbage))
        (setf garbage nil)
        (let ((before (heap-bytes-allocated h)))
          (heap-gc h)
          (assert (< (heap-bytes-allocated h) before)))
        (assert (= (length big) 100000))
        (assert (every (lambda (x) (eql x 7)) big))
        (assert (eq (object-heap big) h))))))

(with-test (:name (:process-heap :heap-gc :weak-pointers))
  (with-test-heap (h :gc-threshold 0)
    (with-heap (h)
      (let* ((live (list 1))
             (wp-live (make-weak-pointer live))
             (wp-dead (make-weak-pointer (list 2)))
             (wp-global (make-weak-pointer (without-heap (list 3)))))
        (heap-gc h)
        (assert (eq (weak-pointer-value wp-live) live))
        (assert (null (weak-pointer-value wp-dead)))
        (assert (equal (weak-pointer-value wp-global) '(3)))))))

(with-test (:name (:process-heap :heap-gc :repeated))
  (with-test-heap (h :gc-threshold 0)
    (with-heap (h)
      (let ((keep (make-array 100 :initial-element nil)))
        (dotimes (round 20)
          (dotimes (i 10000)
            (setf (aref keep (mod i 100)) (list round i)))
          (heap-gc h)
          (dotimes (i 100)
            (assert (= (first (aref keep i)) round))))
        (assert (= (heap-gc-count h) 20))))))

(with-test (:name (:process-heap :automatic-collection))
  (with-test-heap (h :gc-threshold (* 128 1024))
    (with-heap (h)
      (let ((keep (make-array 50 :initial-element nil)))
        (dotimes (i 100000)
          (setf (aref keep (mod i 50)) (make-list 8 :initial-element i)))
        (assert (> (heap-gc-count h) 0))
        (assert (< (heap-bytes-allocated h) (* 4 1024 1024)))
        (dotimes (i 50)
          (assert (= (length (aref keep i)) 8)))))))

(with-test (:name (:process-heap :global-gc-preserves-heap-objects))
  (with-test-heap (h :gc-threshold 0)
    (let (obj)
      (with-heap (h)
        (setf obj (list (make-array 10 :initial-element :x)
                        (copy-seq "text")
                        (list 1 2 3)))
        ;; Global objects referenced only from the heap must survive
        ;; global collections.
        (setf (aref (first obj) 0) (without-heap (make-array 5 :initial-element :g))))
      (dotimes (i 3) (sb-ext:gc :full t))
      (assert (equal (third obj) '(1 2 3)))
      (assert (string= (second obj) "text"))
      (assert (equalp (aref (first obj) 0) #(:g :g :g :g :g)))
      (with-heap (h)
        (heap-gc h)
        (assert (equalp (aref (first obj) 0) #(:g :g :g :g :g)))
        (assert (null (verify-heap h)))))))

(with-test (:name (:process-heap :release-returns-pages))
  (let ((h (make-heap :gc-threshold 0)))
    (with-heap (h)
      (let ((keep (make-array 16 :initial-element nil)))
        (dotimes (i 10000) (setf (aref keep (mod i 16)) (make-array 100)))))
    (assert (> (heap-page-count h) 10))
    (release-heap h)
    (assert (zerop (heap-page-count h)))
    (assert (zerop (heap-bytes-allocated h)))))

;;; --- Limits ---

(with-test (:name (:process-heap :hard-limit))
  (with-test-heap (h :gc-threshold 0 :hard-limit (* 1024 1024))
    (with-heap (h)
      (let ((keep nil))
        ;; A storage-condition, like HEAP-EXHAUSTED-ERROR, so not an ERROR.
        (assert (eq :caught
                    (handler-case (dotimes (i 1000000)
                                    (push (make-array 100) keep))
                      (process-heap-exhausted-error () :caught))))
        (assert (<= (heap-bytes-allocated h) (* 1024 1024)))
        ;; Still usable after collecting.
        (setf keep nil)
        (heap-gc h)
        (assert (equal (make-list 3 :initial-element 1) '(1 1 1)))))))

(with-test (:name (:process-heap :exhausted-error-is-storage-condition))
  (assert (subtypep 'process-heap-exhausted-error 'storage-condition))
  (assert (not (subtypep 'process-heap-exhausted-error 'error))))

(with-test (:name (:process-heap :hard-limit :condition-is-global))
  (with-test-heap (h :gc-threshold 0 :hard-limit (* 512 1024))
    (let ((condition nil))
      (with-heap (h)
        (handler-case (let ((keep nil))
                        (loop (push (make-array 1000) keep)))
          (process-heap-exhausted-error (c) (setf condition c))))
      (assert condition)
      (assert (null (object-heap condition))))))

;;; --- Copying ---

(with-test (:name (:process-heap :copy-for-transfer :types))
  (with-test-heap (h)
    (let (src)
      (with-heap (h)
        (setf src (list "string" #(1 2 3) (make-array 3 :element-type '(unsigned-byte 8)
                                                         :initial-contents '(1 2 3))
                        (expt 2 100) 1/3 2.5d0 #c(1 2) #c(1.5d0 2.5d0)
                        (make-symbol "UNINTERNED") :keyword
                        (make-array '(2 2) :initial-element 0)
                        (make-array 3 :fill-pointer 2 :adjustable t :initial-element 'a))))
      (let ((copy (copy-for-transfer src)))
        (assert (not (eq copy src)))
        (assert (null (object-heap copy)))
        (assert (equal (first copy) "string"))
        (assert (null (object-heap (first copy))))
        (assert (equalp (second copy) #(1 2 3)))
        (assert (equalp (third copy) (third src)))
        (assert (= (fourth copy) (expt 2 100)))
        (assert (= (fifth copy) 1/3))
        (assert (= (sixth copy) 2.5d0))
        (assert (= (seventh copy) #c(1 2)))
        (assert (= (eighth copy) #c(1.5d0 2.5d0)))
        ;; Symbols are always global (and so are their names), hence shared.
        (assert (string= (symbol-name (ninth copy)) "UNINTERNED"))
        (assert (eq (ninth copy) (ninth src)))
        (assert (null (object-heap (ninth src))))
        (assert (null (object-heap (symbol-name (ninth src)))))
        (assert (eq (tenth copy) :keyword))
        (let ((m (nth 10 copy)))
          (assert (equal (array-dimensions m) '(2 2)))
          (assert (null (object-heap m))))
        (let ((v (nth 11 copy)))
          (assert (= (fill-pointer v) 2))
          (assert (adjustable-array-p v))
          (assert (eq (aref v 0) 'a)))))))

(with-test (:name (:process-heap :copy-for-transfer :sharing-and-cycles))
  (with-test-heap (h)
    (let (src)
      (with-heap (h)
        (let ((shared (list 1 2)))
          (setf src (list shared shared (vector shared)))
          (setf (cdr (last (first src))) (first src))))
      (let ((copy (copy-for-transfer src)))
        (assert (eq (first copy) (second copy)))
        (assert (eq (aref (third copy) 0) (first copy)))
        (assert (eq (cddr (first copy)) (first copy)))
        (assert (null (object-heap (first copy))))))))

(with-test (:name (:process-heap :copy-for-transfer :global-objects-are-shared))
  (with-test-heap (h)
    (let* ((global (list 1 2))
           src)
      (with-heap (h)
        (setf src (list global (vector global))))
      (let ((copy (copy-for-transfer src)))
        (assert (eq (first copy) global))
        (assert (eq (aref (second copy) 0) global))))))

(with-test (:name (:process-heap :copy-for-transfer :untransferable))
  (with-test-heap (h)
    (flet ((try (thunk)
             (let (obj)
               (with-heap (h) (setf obj (funcall thunk)))
               (assert-error (copy-for-transfer obj) untransferable-object))))
      (try (lambda () (let ((n 1)) (lambda () (incf n)))))
      (try (lambda () (make-weak-pointer (list 1))))
      (try (lambda () (sb-thread:make-mutex)))
      (try (lambda () (let ((ht (make-hash-table :weakness :key)))
                        (setf (gethash (list 1) ht) 1)
                        ht))))))

;;; --- Messages ---

(with-test (:name (:process-heap :send-and-receive))
  (with-test-heap (a)
    (with-test-heap (b)
      (with-heap (a)
        (send-message b (list (copy-seq "one") (vector 1 2)))
        (send-message b 42)
        (send-message b (make-hash-table)))
      (assert (= (heap-mailbox-count b) 3))
      (assert (plusp (heap-mailbox-bytes b)))
      (with-heap (b)
        (multiple-value-bind (msg found from) (receive-message)
          (assert found)
          (assert (eq from a))
          (assert (equal (first msg) "one"))
          (assert (eq (object-heap msg) b))
          (assert (eq (object-heap (first msg)) b)))
        (multiple-value-bind (msg found from) (receive-message)
          (assert found)
          (assert (eq from a))
          (assert (eql msg 42)))
        (multiple-value-bind (msg found) (receive-message)
          (assert found)
          (assert (hash-table-p msg))
          (assert (eq (object-heap msg) b)))
        (multiple-value-bind (msg found from) (receive-message)
          (assert (null found))
          (assert (null msg))
          (assert (null from))))
      (assert (zerop (heap-mailbox-count b)))
      (assert (zerop (heap-mailbox-bytes b))))))

(with-test (:name (:process-heap :receive-requires-current))
  (with-test-heap (b)
    (send-message b (list 1))
    (assert-error (receive-message :heap b) heap-not-current-error)))

(with-test (:name (:process-heap :messages-survive-collections))
  (with-test-heap (a :gc-threshold 0)
    (with-test-heap (b :gc-threshold 0)
      (with-heap (a)
        (dotimes (i 100)
          (send-message b (list i (make-string 50 :initial-element #\m))))
        (dotimes (i 10000) (make-list 5))
        (heap-gc a))
      (sb-ext:gc :full t)
      (with-heap (b)
        (dotimes (i 10000) (make-list 5))
        (heap-gc b)
        (dotimes (i 100)
          (multiple-value-bind (msg found) (receive-message)
            (assert found)
            (assert (= (first msg) i))
            (assert (= (length (second msg)) 50))))
        (heap-gc b)
        (assert (null (verify-heap b)))))))

(with-test (:name (:process-heap :send-from-global))
  (with-test-heap (b)
    (let ((global (list 1 2 3)))
      (send-message b global)
      (with-heap (b)
        (multiple-value-bind (msg found from) (receive-message)
          (assert found)
          (assert (null from))
          ;; A global message is shared, not copied.
          (assert (eq msg global)))))))

(with-test (:name (:process-heap :send-untransferable-leaves-heap-clean))
  (with-test-heap (a)
    (with-test-heap (b)
      (with-heap (a)
        (let ((bad (list (sb-thread:make-mutex))))
          (assert-error (send-message b bad) untransferable-object)))
      (assert (zerop (heap-mailbox-count b)))
      (assert (eq (current-heap) nil)))))

(with-test (:name (:process-heap :release-drops-mailbox))
  (let ((b (make-heap)))
    (send-message b (make-array 1000))
    (assert (= (heap-mailbox-count b) 1))
    (release-heap b)
    (assert (zerop (heap-mailbox-count b)))))

;;; --- Verification ---

(with-test (:name (:process-heap :verify-heap :clean))
  (with-test-heap (h)
    (with-heap (h)
      (let ((x (list (make-array 10) "s" (without-heap (list :global)))))
        (assert (null (verify-heap h)))
        (assert (eq (object-heap x) h))))))

(with-test (:name (:process-heap :verify-heap :cross-heap-reference))
  ;; Deliberate violations, so the store barrier is off for A.
  (with-test-heap (a :check-stores nil)
    (with-test-heap (b)
      (let (vec other)
        (with-heap (b) (setf other (list :b)))
        (with-heap (a)
          (setf vec (make-array 2))
          ;; Deliberate violation: A's vector points into B.
          (setf (aref vec 0) other)
          (let ((violations (verify-heap a)))
            (assert (= (length violations) 1))
            (assert (eq (first (first violations)) vec)))
          (setf (aref vec 0) nil)
          (assert (null (verify-heap a))))))))

(with-test (:name (:process-heap :verify-all-heaps :global-to-heap-reference))
  (with-test-heap (h :check-stores nil)
    (let ((holder (make-array 1 :initial-element nil)))
      (with-heap (h)
        (setf (aref holder 0) (list :local)))
      (let ((violations (verify-all-heaps)))
        (assert (find holder violations :key #'first)))
      (setf (aref holder 0) nil)
      (assert (null (verify-all-heaps))))))

(with-test (:name (:process-heap :finalizers-rejected))
  (with-test-heap (h)
    (with-heap (h)
      (let ((obj (list 1)))
        (assert-error (finalize obj (lambda ())))))))

;;; --- Store barrier ---

(with-test (:name (:process-heap :store-barrier :escape))
  (with-test-heap (h)
    (let ((holder (make-array 1 :initial-element nil)))
      (with-heap (h)
        (let ((local (list 1)))
          (assert (eq :caught
                      (handler-case (progn (setf (aref holder 0) local) :stored)
                        (process-heap-store-error (c)
                          (assert (eq (process-heap-store-error-kind c) :escape))
                          (assert (eq (process-heap-store-error-object c) holder))
                          (assert (eq (process-heap-store-error-value c) local))
                          :caught))))
          ;; The store was not performed.
          (assert (null (aref holder 0)))
          ;; Global values, immediates and same-heap values are fine.
          (setf (aref holder 0) (without-heap (list 2)))
          (setf (aref holder 0) 17)
          (let ((mine (make-array 1)))
            (setf (aref mine 0) local)
            (setf (aref mine 0) holder))
          (assert (eql (aref holder 0) 17))))
      (assert (null (verify-all-heaps))))))

;;; Two store paths with barriers of their own: a global name's function
;;; cell and double-word compare-and-swap.
(with-test (:name (:process-heap :store-barrier :fdefinition-and-cas-pair))
  (with-test-heap (h)
    (let ((name (make-symbol "PROCESS-FUN"))
          (holder (make-array 4 :initial-element nil))
          #+x86-64 (cell (cons nil nil)))
      (with-heap (h)
        (let ((local (let ((n 0)) (lambda () (incf n)))))
          (assert (eq (object-heap local) h))
          (assert-error (sb-impl::fset name local) process-heap-store-error)
          (assert (not (fboundp name)))
          (assert-error (sb-vm::%vector-cas-pair holder 0 nil nil local local)
                        process-heap-store-error)
          (assert (null (aref holder 0)))
          #+x86-64
          (assert-error (sb-vm::%cons-cas-pair cell nil nil local local)
                        process-heap-store-error)
          #+x86-64
          (assert (null (car cell)))
          ;; Global and same-heap values go through.
          (sb-impl::fset name #'identity)
          (assert (eq (fdefinition name) #'identity))
          (let ((mine (make-array 2 :initial-element nil)))
            (sb-vm::%vector-cas-pair mine 0 nil nil local local)
            (assert (eq (aref mine 0) local))))))
    (assert (null (verify-all-heaps)))))

(with-test (:name (:process-heap :store-barrier :compound-fdefn-is-global))
  (with-test-heap (h)
    (let ((name (list 'setf (make-symbol "PROCESS-FUN"))))
      (with-heap (h)
        (let ((local (let ((count 0))
                       (lambda () (incf count)))))
          (assert (eq (object-heap local) h))
          (assert-error (sb-impl::fset name local) process-heap-store-error)
          (assert (not (fboundp name)))
          (sb-impl::fset name #'identity)
          (assert (eq (fdefinition name) #'identity))
          (let ((local-name (list 'setf (make-symbol "LOCAL-PROCESS-FUN"))))
            (assert (eq (object-heap local-name) h))
            (assert-error (sb-impl::fset local-name #'identity)
                          process-heap-store-error)
            (assert (not (fboundp local-name)))))))
    (assert (null (verify-all-heaps)))))

(with-test (:name (:process-heap :store-barrier :fdefn-resize-is-global))
  (with-test-heap (h)
    (let* ((before-state sb-impl::*fdefns*)
           (before (car before-state))
           (before-count (cdr before-state))
           (before-contents (copy-seq before))
           (names (loop repeat (length before)
                        collect (list 'sb-pcl::fast-method
                                      (make-symbol "PROCESS-FUN")
                                      (list 't 'cons)))))
      (unwind-protect
           (with-heap (h)
             (dolist (name names)
               (sb-impl::fset name #'identity)
               (unless (eq before (car sb-impl::*fdefns*))
                 (return)))
             (assert (not (eq before (car sb-impl::*fdefns*))))
             (assert (zerop (sb-vm::object-owner sb-impl::*fdefns*)))
             (assert (zerop (sb-vm::object-owner (car sb-impl::*fdefns*)))))
        (without-heap
          (setf sb-impl::*fdefns* before-state
                (cdr before-state) before-count)
          (replace before before-contents)))
      (assert (null (verify-all-heaps))))))

(with-test (:name (:process-heap :store-barrier :explicit-check-policy))
  (with-test-heap (h)
    (with-heap (h)
      (let ((local (list :local))
            (caught nil))
        (handler-bind ((process-heap-store-error
                         (lambda (condition)
                           (setf caught condition)
                           (continue condition))))
          (sb-vm::check-process-heap-store 'fdefinition local))
        (assert (eq (process-heap-store-error-kind caught) :escape))
        (assert (eq (process-heap-store-error-object caught) 'fdefinition))
        (assert (eq (process-heap-store-error-value caught) local)))))
  (with-test-heap (h :check-stores :record)
    (reset-heap-violations)
    (with-heap (h)
      (sb-vm::check-process-heap-store 'fdefinition (list :local)))
    (assert (find 'fdefinition (heap-violations) :key #'first))
    (reset-heap-violations))
  (with-test-heap (h :check-stores nil)
    (reset-heap-violations)
    (with-heap (h)
      (sb-vm::check-process-heap-store 'fdefinition (list :local)))
    (assert (null (heap-violations)))))

(with-test (:name (:process-heap :store-barrier :structure-and-cons-and-symbol))
  (with-test-heap (h)
    (let ((global-cons (cons nil nil))
          (global-heap (make-heap :name "other"))
          (sym (make-symbol "GLOBAL-VAR")))
      (unwind-protect
           (with-heap (h)
             (let ((local (make-string 3)))
               (assert-error (setf (car global-cons) local) process-heap-store-error)
               (assert-error (setf (cdr global-cons) local) process-heap-store-error)
               ;; The symbol's global value cell is global.
               (assert-error (setf (symbol-value sym) local) process-heap-store-error)
               ;; A dynamic binding is a root of the process, not a violation.
               (progv (list sym) (list local)
                 (setf (symbol-value sym) (list local)))
               (assert-error (setf (heap-name global-heap) local)
                             process-heap-store-error)
               (assert (null (car global-cons)))
               (assert (not (boundp sym)))))
        (release-heap global-heap)))))

(with-test (:name (:process-heap :store-barrier :cross-heap))
  (with-test-heap (a)
    (with-test-heap (b)
      (let (a-obj)
        (with-heap (a) (setf a-obj (make-array 2 :initial-element 0)))
        (with-heap (b)
          (let ((b-obj (make-array 2)))
            (assert (eq :caught
                        (handler-case (progn (setf (aref b-obj 0) a-obj) :stored)
                          (process-heap-store-error (c)
                            (assert (eq (process-heap-store-error-kind c) :cross-heap))
                            :caught))))
            ;; A global object (b-obj is not) may be stored anywhere.
            (setf (aref b-obj 1) (without-heap (list 1)))))))))

(with-test (:name (:process-heap :store-barrier :continue-restart))
  (with-test-heap (h)
    (let ((holder (make-array 1 :initial-element nil)))
      (with-heap (h)
        (let ((local (list :escaped)))
          (handler-bind ((process-heap-store-error #'continue))
            (setf (aref holder 0) local))
          (assert (eq (aref holder 0) local))
          ;; Now a real violation exists; the verifier reports it.
          (assert (find holder (verify-all-heaps) :key #'first))
          (setf (aref holder 0) nil)))
      (assert (null (verify-all-heaps))))))

(with-test (:name (:process-heap :store-barrier :record-mode))
  (with-test-heap (h :check-stores :record)
    (let ((holder (make-array 1 :initial-element nil)))
      (reset-heap-violations)
      (with-heap (h)
        (let ((local (list 1)))
          (setf (aref holder 0) local)
          (assert (eq (aref holder 0) local))
          (assert (eq (heap-check-stores h) :record))))
      (let ((violations (heap-violations)))
        (assert (find holder violations :key #'first)))
      (setf (aref holder 0) nil)
      (reset-heap-violations))))

(with-test (:name (:process-heap :store-barrier :unchecked-and-setf))
  (with-test-heap (h :check-stores nil)
    (let ((holder (make-array 1 :initial-element nil)))
      (with-heap (h)
        (setf (aref holder 0) (list 1))
        (assert (null (heap-check-stores h)))
        (setf (heap-check-stores h) :error)
        (assert-error (setf (aref holder 0) (list 2)) process-heap-store-error)
        (setf (aref holder 0) nil)))))

(with-test (:name (:process-heap :store-barrier :strict))
  (with-test-heap (h :strict t)
    (assert (heap-strict-p h))
    ;; Only pointer stores are checked: storing an immediate cannot create
    ;; a reference, so the tests below store global objects.
    (let ((table (make-hash-table))
          (cell (cons nil nil))
          (global (list :global)))
      (with-heap (h)
        (assert-error (setf (gethash 1 table) global) process-heap-store-error)
        (assert (eq :caught
                    (handler-case (progn (setf (car cell) global) :stored)
                      (process-heap-store-error (c)
                        (assert (eq (process-heap-store-error-kind c) :global))
                        :caught))))
        (assert (null (car cell)))
        ;; Authorized: with the global heap installed there is no check.
        (without-heap (setf (car cell) global))
        (assert (eq (car cell) global))
        ;; Process-owned objects may be mutated freely.
        (let ((mine (make-array 1)))
          (setf (aref mine 0) (list 1))
          (setf (aref mine 0) global))
        (setf (heap-strict-p h) nil)
        (assert (not (heap-strict-p h)))
        (setf (cdr cell) global))
      (assert (eq (cdr cell) global)))))

(with-test (:name (:process-heap :store-barrier :messages-are-checked-safely))
  (with-test-heap (a)
    (with-test-heap (b)
      (with-heap (a)
        (let ((table (make-hash-table :test 'equal)))
          (setf (gethash "k" table) (list 1 2))
          (send-message b (list table (vector (list 3))))))
      (with-heap (b)
        (multiple-value-bind (msg found) (receive-message)
          (assert found)
          (assert (equal (gethash "k" (first msg)) '(1 2)))
          (let ((keep (make-array 1)))
            (setf (aref keep 0) msg))
          (assert (null (verify-heap))))))))

;;; --- Generations ---

(with-test (:name (:process-heap :generations :minor-promotes-and-major-reclaims))
  (with-test-heap (h :gc-threshold 0 :fullsweep-after 0)
    (with-heap (h)
      (let ((old (make-array 1000 :initial-element nil)))
        (dotimes (i 1000) (setf (aref old i) (make-list 100 :initial-element i)))
        (heap-gc h)
        (assert (= (heap-minor-gc-count h) 1))
        (assert (zerop (heap-major-gc-count h)))
        (let ((promoted (heap-bytes-old h)))
          (assert (> promoted (* 1000 100 16)))
          ;; Old -> young pointers are found through card marks.
          (dotimes (i 1000)
            (setf (aref old i) (make-string 5 :initial-element #\y)))
          (dotimes (i 5000) (make-list 3))
          (heap-gc h)
          (assert (= (heap-minor-gc-count h) 2))
          (dotimes (i 1000)
            (assert (string= (aref old i) "yyyyy")))
          ;; The lists are garbage in the old generation: only a full
          ;; collection reclaims them.
          (assert (>= (heap-bytes-old h) promoted))
          (heap-gc h t)
          (assert (= (heap-major-gc-count h) 1))
          (assert (< (heap-bytes-old h) (floor promoted 4)))
          (dotimes (i 1000)
            (assert (string= (aref old i) "yyyyy")))
          (assert (null (verify-heap h))))))))

(with-test (:name (:process-heap :generations :large-old-object-cards))
  (with-test-heap (h :gc-threshold 0 :fullsweep-after 0)
    (with-heap (h)
      (let ((big (make-array 100000 :initial-element nil)))
        (heap-gc h)                     ; promotes BIG
        (setf (aref big 0) (list :young-1)
              (aref big 50000) (list :young-2)
              (aref big 99999) (list :young-3))
        (dotimes (i 5000) (make-list 3))
        (heap-gc h)
        (assert (equal (aref big 0) '(:young-1)))
        (assert (equal (aref big 50000) '(:young-2)))
        (assert (equal (aref big 99999) '(:young-3)))
        (heap-gc h t)
        (assert (equal (aref big 50000) '(:young-2)))
        (assert (null (verify-heap h)))))))

(with-test (:name (:process-heap :generations :fullsweep-after))
  (with-test-heap (h :gc-threshold 0 :fullsweep-after 3)
    (assert (= (heap-fullsweep-after h) 3))
    (with-heap (h)
      (let ((keep (make-list 10)))
        (dotimes (i 3) (heap-gc h))
        (assert (= (heap-minor-gc-count h) 3))
        (assert (zerop (heap-major-gc-count h)))
        (heap-gc h)
        (assert (= (heap-major-gc-count h) 1))
        (assert (= (length keep) 10))
        (setf (heap-fullsweep-after h) 0)
        (dotimes (i 5) (heap-gc h))
        (assert (= (heap-major-gc-count h) 1))))))

(with-test (:name (:process-heap :generations :automatic-minors))
  (with-test-heap (h :gc-threshold (* 128 1024) :fullsweep-after 4)
    (with-heap (h)
      (let ((keep (make-array 20 :initial-element nil)))
        (dotimes (i 200000)
          (setf (aref keep (mod i 20)) (make-list 8 :initial-element i)))
        (assert (> (heap-minor-gc-count h) 4))
        (assert (> (heap-major-gc-count h) 0))
        (dotimes (i 20) (assert (= (length (aref keep i)) 8)))
        (assert (null (verify-heap h)))))))

(with-test (:name (:process-heap :generations :weak-pointer-old-to-young))
  (with-test-heap (h :gc-threshold 0 :fullsweep-after 0)
    (with-heap (h)
      (let* ((live (list :live))
             (holder (make-array 2 :initial-element nil))
             (wp-live (make-weak-pointer live)))
        (setf (aref holder 0) wp-live)
        (heap-gc h)                     ; everything promoted
        (setf (aref holder 1) (make-weak-pointer (list :dead)))
        (dotimes (i 1000) (make-list 3))
        (heap-gc h)
        (assert (eq (weak-pointer-value wp-live) live))
        (assert (null (weak-pointer-value (aref holder 1))))))))

;;; --- Blocks ---

;;; A heap holding a handful of objects costs one cons block and one
;;; mixed block.
(with-test (:name (:process-heap :blocks :small-footprint))
  (with-test-heap (h :gc-threshold 0)
    (with-heap (h)
      (let ((keep (make-array 2)))
        (setf (aref keep 0) (list 1 2 3)
              (aref keep 1) (make-array 10 :initial-element 0))
        (assert (eq (object-heap keep) h))
        (assert (eq (object-heap (aref keep 0)) h))))
    (assert (= (heap-block-count h) 2))
    (assert (= (heap-bytes-allocated h) 8192))
    (assert (= (heap-page-count h) 2))))

;;; Heaps that share pages allocate and collect independently.
(with-test (:name (:process-heap :blocks :shared-pages))
  (let ((a (make-heap :gc-threshold 0))
        (b (make-heap :gc-threshold 0))
        (na 0) (nb 0))
    (unwind-protect
         (let (keep-a keep-b)
           (dotimes (i 50)
             (with-heap (a)
               (push (list i (make-string 20 :initial-element #\a)) keep-a))
             (with-heap (b)
               (push (list i (make-string 20 :initial-element #\b)) keep-b)))
           (setf na (heap-block-count a) nb (heap-block-count b))
           (assert (and (plusp na) (plusp nb)))
           (flet ((check (list heap char)
                    (loop for (i s) in list
                          for j downfrom 49
                          do (assert (= i j))
                             (assert (eq (object-heap s) heap))
                             (assert (every (lambda (c) (char= c char)) s)))))
             (with-heap (a)
               (dotimes (i 1000) (make-list 5))
               (heap-gc a)
               (heap-gc a t))
             (check keep-a a #\a)
             (check keep-b b #\b)
             (with-heap (b)
               (dotimes (i 1000) (make-list 5))
               (heap-gc b))
             (check keep-a a #\a)
             (check keep-b b #\b)
             (with-heap (a) (assert (null (verify-heap))))
             (with-heap (b) (assert (null (verify-heap))))
             ;; Releasing A leaves B intact, sharing or not.
             (release-heap a)
             (setf a nil)
             (check keep-b b #\b)
             (with-heap (b)
               (dotimes (i 1000) (make-list 5))
               (heap-gc b t)
               (assert (null (verify-heap))))
             (check keep-b b #\b)))
      (when a (release-heap a))
      (release-heap b))))

;;; An object bigger than a block but smaller than a large object takes
;;; a run of blocks within one page.
(with-test (:name (:process-heap :blocks :multi-block-object))
  (with-test-heap (h :gc-threshold 0)
    (with-heap (h)
      (let ((v (make-array 2500 :element-type '(unsigned-byte 64)
                                :initial-element 7)))
        (assert (eq (object-heap v) h))
        (assert (>= (heap-block-count h) 5))
        (dotimes (i 200) (make-array 100))
        (heap-gc h)
        (assert (= (length v) 2500))
        (assert (every (lambda (x) (= x 7)) v))
        (heap-gc h t)
        (assert (every (lambda (x) (= x 7)) v))))))

;;; Blocks emptied by a collection go back, and so does everything on
;;; release.
(with-test (:name (:process-heap :blocks :reclaimed))
  (with-test-heap (h :gc-threshold 0)
    (with-heap (h)
      (let ((keep (list 1))
            (ring (make-array 64)))
        (dotimes (i 20000) (setf (aref ring (mod i 64)) (make-array 10)))
        (fill ring nil)
        (let ((before (heap-block-count h)))
          (assert (> before 4))
          (heap-gc h t)
          (assert (< (heap-block-count h) before)))
        (assert (equal keep '(1)))))
    (release-heap h)
    (assert (zerop (heap-block-count h)))
    (assert (zerop (heap-page-count h)))))

;;; A small message costs a couple of blocks, not pages.
(with-test (:name (:process-heap :blocks :message-footprint))
  (with-test-heap (receiver :gc-threshold 0)
    (with-test-heap (sender :gc-threshold 0)
      (with-heap (sender)
        (send-message receiver (list :hello (make-string 5 :initial-element #\x))))
      (with-heap (receiver)
        ;; Give the receiver its own two blocks first, so that only the
        ;; adopted message adds to the count.
        (let ((warm (list (make-string 1))))
          (assert (eq (object-heap warm) receiver)))
        (let ((before (heap-block-count receiver))
              (msg (receive-message)))
          (assert (equal msg '(:hello "xxxxx")))
          (assert (eq (object-heap msg) receiver))
          (assert (<= (- (heap-block-count receiver) before) 2)))))))

;;; --- Outgoing global-root summaries ---

;;; A global collection keeps a global object alive when only an old
;;; process object refers to it.
(with-test (:name (:process-heap :summary :old-object-keeps-global-alive))
  (with-test-heap (h :gc-threshold 0)
    (let ((wp nil))
      (with-heap (h)
        (let ((holder (make-array 1)))
          (without-heap
            (setf (aref holder 0) (list (copy-seq "global") 1 2))
            (setf wp (make-weak-pointer (aref holder 0))))
          ;; Promote HOLDER so that the global collection relies on the
          ;; summary rather than on walking it.
          (heap-gc h)
          (assert (plusp (heap-outgoing-count h)))
          (sb-ext:gc :full t)
          (assert (weak-pointer-value wp))
          (assert (equal (aref holder 0) '("global" 1 2)))
          (assert (zerop (heap-global-root-count h)))
          ;; The same after a full local collection rebuilt the summary.
          (heap-gc h t)
          (sb-ext:gc :full t)
          (assert (equal (aref holder 0) '("global" 1 2)))))
      ;; Once the heap is gone nothing keeps the global object.
      (release-heap h)
      (sb-ext:gc :full t)
      (assert (null (weak-pointer-value wp))))))

;;; A store into an old object after its promotion marks a card, and the
;;; global collection walks that object.
(with-test (:name (:process-heap :summary :dirty-old-object))
  (with-test-heap (h :gc-threshold 0)
    (with-heap (h)
      (let ((holder (make-array 4 :initial-element nil)))
        (heap-gc h)
        (without-heap
          (setf (aref holder 2) (list (copy-seq "late") 3)))
        (sb-ext:gc :full t)
        (assert (equal (aref holder 2) '("late" 3)))
        (assert (plusp (heap-global-root-count h)))
        ;; The next local collection moves the edge into the summary.
        (let ((before (heap-outgoing-count h)))
          (heap-gc h)
          (assert (> (heap-outgoing-count h) before)))
        (sb-ext:gc :full t)
        (assert (equal (aref holder 2) '("late" 3)))
        (assert (zerop (heap-global-root-count h)))))))

;;; Young objects are walked wholesale.
(with-test (:name (:process-heap :summary :young-object))
  (with-test-heap (h :gc-threshold 0)
    (with-heap (h)
      (let ((young (list nil)))
        (without-heap
          (setf (car young) (make-array 3 :initial-element :y)))
        (sb-ext:gc :full t)
        (assert (equalp (car young) #(:y :y :y)))
        (assert (plusp (heap-global-root-count h)))))))

;;; A large old object gets the same treatment as a small one.
(with-test (:name (:process-heap :summary :large-old-object))
  (with-test-heap (h :gc-threshold 0)
    (with-heap (h)
      (let ((big (make-array 20000 :initial-element nil)))
        (without-heap
          (setf (aref big 19999) (list :first)))
        ;; The first collection promotes BIG; the second scans and
        ;; clears the card the store above marked while it was young.
        (heap-gc h)
        (heap-gc h)
        (sb-ext:gc :full t)
        (assert (equal (aref big 19999) '(:first)))
        (assert (zerop (heap-global-root-count h)))
        (without-heap
          (setf (aref big 10000) (list :second)))
        (sb-ext:gc :full t)
        (assert (equal (aref big 10000) '(:second)))
        (assert (= (heap-global-root-count h) 1))))))

;;; The walk of a promoted heap is independent of its size, after a
;;; minor or a full collection, and whether the object stored into while
;;; young was small or large (the larger vector is a large object on
;;; every backend).
(with-test (:name (:process-heap :summary :bounded-global-walk))
  (dolist (n '(2000 20000))
    (dolist (full '(nil t))
      (with-test-heap (h :gc-threshold 0)
        (with-heap (h)
          (let ((keep (make-array n)))
            (dotimes (i n) (setf (aref keep i) (list i (make-string 8))))
            (heap-gc h full)
            (sb-ext:gc)
            (assert (zerop (heap-global-root-count h)) ()
                    "~D heap objects walked (n=~D, full=~A)"
                    (heap-global-root-count h) n full)
            (dotimes (i n)
              (assert (= (first (aref keep i)) i)))))))))

;;; --- Shared binaries ---

(with-test (:name (:process-heap :shared-binary :basics))
  (with-test-heap (h :gc-threshold 0)
    (with-heap (h)
      (let ((b (make-shared-binary #(1 2 3)))
            (z (make-shared-binary 16))
            (s (make-shared-binary "text" :element-type 'character))
            (mine (make-array 3 :element-type '(unsigned-byte 8))))
        (assert (null (object-heap b)))
        (assert (shared-binary-p b))
        (assert (shared-binary-p z))
        (assert (shared-binary-p s))
        (assert (equalp b #(1 2 3)))
        (assert (= (length z) 16))
        (assert (every #'zerop z))
        (assert (string= s "text"))
        (assert (eq (object-heap mine) h))
        (assert (not (shared-binary-p mine)))
        (assert (not (shared-binary-p (make-array 3))))
        (assert (not (shared-binary-p 42)))))))

;;; A shared binary is sent by reference, and a global collection
;;; reclaims it once no heap holds it.
(with-test (:name (:process-heap :shared-binary :sent-by-reference))
  (let ((sender (make-heap :gc-threshold 0))
        (receiver (make-heap :gc-threshold 0))
        (wp nil))
    (unwind-protect
         (progn
           (with-heap (receiver)
             (let ((warm (list (make-string 1))))
               (assert (eq (object-heap warm) receiver))))
           (with-heap (sender)
             (let ((payload (make-shared-binary 100000)))
               (fill payload 7)
               (without-heap (setf wp (make-weak-pointer payload)))
               (send-message receiver (list :blob payload))))
           (with-heap (receiver)
             (let ((before (heap-block-count receiver))
                   (msg (receive-message)))
               (assert (eq (first msg) :blob))
               (assert (eq (second msg) (weak-pointer-value wp)))
               (assert (shared-binary-p (second msg)))
               (assert (= (length (second msg)) 100000))
               (assert (every (lambda (x) (= x 7)) (second msg)))
               (assert (<= (- (heap-block-count receiver) before) 2))
               ;; The receiver's own collections keep it.
               (heap-gc receiver)
               (heap-gc receiver t)
               (sb-ext:gc :full t)
               (assert (weak-pointer-value wp))
               (assert (every (lambda (x) (= x 7)) (second msg))))))
      (release-heap sender)
      (release-heap receiver))
    (sb-ext:gc :full t)
    (assert (null (weak-pointer-value wp)))))
