;;;; -*-  Lisp -*-

(defpackage :sb-fiber
  (:use :cl :sb-alien :sb-ext)
  #+sb-process-heaps
  (:import-from :sb-kernel
                #:process-heap-exhausted-error
                #:process-heap-store-error
                #:process-heap-store-error-object
                #:process-heap-store-error-value
                #:process-heap-store-error-kind)
  (:export
   #:*current-fiber*
   #:current-fiber
   #:*default-fiber-stack-size*
   #:*default-fiber-binding-stack-size*
   #:fiber
   #:fiberp
   #:make-fiber
   #:make-main-fiber
   #:with-fiber-thread
   #:release-fiber
   #:fiber-name
   #:fiber-thread
   #:fiber-return-fiber
   #:switch-fiber
   #:resume-fiber
   #:yield-fiber
   #:join-fiber
   #:interrupt-fiber
   #:with-interrupted-fiber
   #:fiber-condition
   #:fiber-alive-p
   #:fiber-main-p
   #:fiber-released-p
   #:fiber-state
   #:fiber-control-stack-size
   #:fiber-control-stack-usage
   #:fiber-binding-stack-size
   #:fiber-binding-stack-usage
   #:with-fiber
   #:with-fiber-pinned
   #:fiber-pinned-p
   #:fiber-pin-count
   #:fiber-migrate
   ;; Conditions
   #:fiber-error
   #:fiber-error-fiber
   #:dead-fiber-error
   #:pinned-fiber-error
   #:pinned-fiber-error-depth
   #:fiber-thread-mismatch-error
   #:fiber-thread-mismatch-error-role
   #:fiber-state-error
   #:fiber-state-error-state
   #:fiber-state-error-expected
   #:no-current-fiber-error
   #:no-current-fiber-error-operation
   #:heap-fiber-escape
   #:heap-fiber-escape-fiber
   #:heap-fiber-escape-condition-type
   #:heap-fiber-escape-message
   ;; Process heaps
   #:heap
   #:heap-p
   #:make-heap
   #:release-heap
   #:heap-name
   #:heap-id
   #:heap-fiber
   #:heap-alive-p
   #:heap-released-p
   #:current-heap
   #:object-heap
   #:with-heap
   #:without-heap
   #:heap-gc
   #:heap-check-stores
   #:heap-strict-p
   #:heap-bytes-allocated
   #:heap-bytes-live
   #:heap-bytes-since-gc
   #:heap-gc-count
   #:heap-minor-gc-count
   #:heap-major-gc-count
   #:heap-bytes-old
   #:heap-fullsweep-after
   #:heap-gc-run-time
   #:heap-page-count
   #:heap-block-count
   #:heap-outgoing-count
   #:heap-global-root-count
   #:local-gc-concurrency-peak
   #:heap-mailbox-count
   #:heap-mailbox-bytes
   #:*default-heap-gc-threshold*
   #:fiber-heap
   #:copy-for-transfer
   #:globalize
   #:make-shared-binary
   #:shared-binary-p
   #:send-message
   #:receive-message
   #:verify-heap
   #:verify-all-heaps
   #:heap-violations
   #:reset-heap-violations
   #:heap-reference-checking
   ;; Heap conditions
   #:heap-error
   #:heap-error-heap
   #:dead-heap-error
   #:heap-in-use-error
   #:heap-not-current-error
   #:no-current-heap-error
   #:no-current-heap-error-operation
   #:untransferable-object
   #:untransferable-object-object
   #:cross-heap-reference
   #:cross-heap-reference-object
   #:process-heap-exhausted-error
   #:process-heap-store-error
   #:process-heap-store-error-object
   #:process-heap-store-error-value
   #:process-heap-store-error-kind))

(eval-when (:compile-toplevel :load-toplevel :execute)
  (setf (sb-int:system-package-p (find-package "SB-FIBER")) t))
